server:
  port: 8081

spring:
  application:
    name: employee
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:parking-db
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:db/migration/h2



logging.level.com.jinternals: DEBUG

